### PR TITLE
bump Integreatly version to 1.5.0

### PR DESCRIPTION
**Pull request by davidffrench**
##### SUMMARY

- Bumping Integreatly workshop default version to 1.5.0

##### ISSUE TYPE
- New config Pull Request

##### COMPONENT NAME
Integreatly

##### ADDITIONAL INFORMATION
Full Integreatly 1.5.0 release testing has now been completed and the final release tag of release-1.5.0 has been created. Bumping the version to 1.5.0 from 1.5.0-alpha here.

We will also be removing older versions, `1.3.0` and `1.4.0` but this will come in another PR later today or tomorrow. 

Previous PR to add 1.5.0-alpha - https://github.com/redhat-cop/agnosticd/pull/634

### CODE REVIEW

**Comment by davidffrench** [comment]
@maleck13 @pmccarthy Confirming our decision to remove 1.3.0 and 1.4.0 from RHPDS?

**Comment by maleck13** [comment]
I don't recall that decision being made? We have no clusters on those versions so prob fine. What version does DIL use?

**Comment by davidffrench** [comment]
@maleck13 Sorry, you may not have been involved in the discussions. I am 99% sure they are using 1.4.1 but we will wait for confirmation from Hugo and Monica and submit a second PR to remove these versions once we have confirmation.

**Comment by trepel** [comment]
@NonyNo3lle @fridim Mind taking a look when you get a chance, please? Thanks.

**Pull request merged**
