### PR TITLE
RHTE ML Workflows Workshop

### PR DESCRIPTION
**Pull request by willb**
##### SUMMARY

This is a role for the ML Workflows Workshop at RHTE.  This pull request depends on #569

##### ISSUE TYPE

- New role Pull Request

##### COMPONENT NAME

- `ansible/roles/ocp4-workload-ml-workflows-workshop`

##### ADDITIONAL INFORMATION

Task order should be

* `ocp4-workload-rhte-analytics_data_ocp_infra` Run once per cluster, defining `jupyter_notebook_memory=6Gi` and `deploy_odh_cr=true`
* `ocp4-workload-rhte-analytics_data_ocp_workshop` Run once per user in the class, supply the name of the OCP user with the variable `user_name`, and supply the user's project name in the variable `project_name`; also define `jupyter_notebook_memory=6Gi` and `deploy_odh_cr=true`.
* `ocp4-workload-ml-workflows-workshop` with the name of the OCP user with the variable `user_name` and the user's project name in the variable `project_name`.

### CODE REVIEW

**Comment by willb** [comment]
(cc @LaVLaS @sophwats)

**Comment by wkulhanek** [comment]
The role this depends on is failing ansible syntax checks. Thereore this one is too. Can't merge until resolved.

**Comment by stencell** [comment]
Closing and reopening to trigger a new CI build

**Comment by willb** [comment]
I'll rebase on Landon's update and add some additional fixes.

**Comment by sborenst** [comment]
@willb Lots os merge issues on this PR, can you examine?

**Comment by willb** [comment]
@sborenst yes, thanks -- I had to do some git archaeology to rebase this on the squashed PR I'd been building off of.  Things should be sorted now.

**Comment by stencell** [comment]
Much cleaner...merged.

**Pull request merged**
