### PR TITLE
Osp public hostname

### PR DESCRIPTION
**Pull request by ezr-ondrej**
##### SUMMARY
Set osp `public_dns_hostname` fact for all instances that have `public_dns: true`

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Cloud provider `osp`

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Should get review from @fridim!

**Comment by ezr-ondrej** [comment]
After a discussion, it apprears it could be a good idea to have a `public_dns` for every host with a floating IP. That case, we could just drop the `public_dns` instance variable and be done with it.

**Comment by NonyNo3lle** [comment]
@ezr-ondrej @fridim can we close this one? It seems old and no longer needed

**Comment by ezr-ondrej** [comment]
If it wasn't addressed by someone else, it would be nice to have. I can finish it off if I get an opinion. But I'm ok if we close as well, it's not a show stopper

**Comment by fridim** [comment]
closing, as discussed

**Pull request closed without merging**
