### PR TITLE
yamllint formatting cleanup for ocp-workload-amq-enmasse

### PR DESCRIPTION
**Pull request by ritesh97-rh**
##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp-workload-amq-enmasse

### CODE REVIEW

**Comment by stencell** [comment]
@btison @nandanj Is this role needed? The readme states it is for the `AMQ Enmasse Foundations` course, but i don't even see that in the LMS? If it is not used, we can archive and eventually delete.

**Review by btison — COMMENTED** [review]
@stencell This workload is obsolete. The current course name is `AMQ Online Foundations`, which uses a OCP4 sandbox as lab environment (AgnosticV sandboxes-gpte/OCP4_AMQ_ONLINE_FOUNDATIONS)

**Comment by jkupferer** [comment]
@btison I had opened a PR to remove this workload, but @fridim caught that this workload is referenced in the catalog item you mentioned?
https://github.com/redhat-gpe/agnosticv/blob/master/sandboxes-gpte/OCP4_AMQ_ONLINE_FOUNDATIONS/common.yaml#L55

**Comment by btison** [comment]
@jkupferer

>This workload is obsolete. The current course name is `AMQ Online Foundations`, which uses a OCP4 sandbox as lab environment (AgnosticV sandboxes-gpte/OCP4_AMQ_ONLINE_FOUNDATIONS)

My bad. The current course uses the AgnosticV `sandboxes-gpte/ELT_OCP4_AMQ_ONLINE_FOUNDATIONS` catalog item. From what I can see `sandboxes-gpte/OCP4_AMQ_ONLINE_FOUNDATIONS` is obsolete as well.

**Pull request closed without merging**
