### PR TITLE
Add role ocp4_workload_image_registry

### PR DESCRIPTION
**Pull request by jkupferer**
##### SUMMARY

Add role ocp4_workload_image_registry

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Role ocp4_workload_image_registry

### CODE REVIEW

**Comment by wkulhanek** [comment]
@jkupferer Do we actually need that role? ocp4_workload_opentlc_production already has that capability. You could just use that role and set the other customizations off if a registry route is all you need.

**Comment by jkupferer** [comment]
@wkulhanek It seems to me that `ocp4_workload_opentlc_production` does too much. Following @tonykay 's principle of Roles should be targeted to specific functions?

**Comment by jkupferer** [comment]
Also, a role that does "opentlc_production" stuff just doesn't seem clearly defined. When I saw this role existed I guessed that it was specific to maintaining our OpenTLC shared clusters, that it wasn't meant to be used in other ways?

**Comment by wkulhanek** [comment]
It might be oddly named (probably better would be "cluster settings" or something. But that doesn't take away from the fact that this role would duplicate existing functionality. Which isn't necessary. I really don't subscribe to the two task "let's add more overhead" roles.

**Comment by jkupferer** [comment]
Cluster settings is also too vague of a role concept. A single role should not be configuring the registry and also self-provisioner access. Everything in OCP4 is a cluster setting? The production role seems like a miscellaneous grab-bag?

As @NonyNo3lle said in chat, I think we may need a tie-breaker vote.

**Comment by NonyNo3lle** [comment]
@fridim your feedback would be good here too

**Pull request closed without merging**
