### PR TITLE
Add role infra_osp_bastion_on_openshift_network

### PR DESCRIPTION
**Pull request by jkupferer**
##### SUMMARY

Add role infra_osp_bastion_on_openshift_network to add bastion to OpenShift node network.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Role infra_osp_bastion_on_openshift_network

### CODE REVIEW

**Review by rut31337 — APPROVED** [review]
LGTM

**Review by rut31337 — APPROVED** [review]
LGTM

**Review by wkulhanek — CHANGES_REQUESTED** [review]
I don't see a conditional to turn this on or off?

**Comment by jkupferer** [comment]
> I don't see a conditional to turn this on or off?

It is a role... so the role would only be included when this feature is desired. Am I missing something?

**Review by wkulhanek — APPROVED** [review]

**Pull request merged**
