### PR TITLE
Adding OpenShift Ansible Better Together workshop

### PR DESCRIPTION
**Pull request by deweya**
Adding OpenShift Ansible Better Together workshop for dev track.

Is a copy of the ocp4-workshop with our stuff added on top. Ours config is called "openshift-ansible-better-together"

Essentially, upped the user count to 30, are installing docker and operator-sdk on the bastions, and created a workload called "ocp4-workload-openshift-ansible" that will create CRDs to the cluster.

### CODE REVIEW

**Comment by wkulhanek** [comment]
Is it really necessary to fork this config rather than just using workshop with the right workloads and parameters? How will you keep up with future changes?

**Comment by deweya** [comment]
From what I can tell, the only thing we really need on top of the ocp4 base config is docker and operator-sdk installed on the bastion. Part of the lab will include testing and building an Ansible operator with the operator-sdk. 

Everything else we should be able to configure with env_vars.yaml and a custom workload. Perhaps we could further configure the bastions with a post-provisioning script, but out of the box the config doesn’t provide everything we need.

**Comment by deweya** [comment]
@wkulhanek Could you please review again? Now that I understand a little better, I realized I could do what I needed with just a custom workload. So I removed the new config and moved the logic I had there into a custom workload.

**Comment by wkulhanek** [comment]
LGTM. Thanks @deweya for making these changes. MUCH less risky.... I have a feeling we'll be doing some surgery on ocp4-workshop shortly and this will keep you whole. :-)

**Pull request merged**
