### PR TITLE
Basic config for AAP2 Infra CIs first targetted at AWS/EC2

### PR DESCRIPTION
**Pull request by tonykay**
##### SUMMARY

Simple new base config intended for all AAP2 CIs requiring VMs/Instances

- Supports AWS (OSP would be a Sha 5 minute job)

Will be used first by Automate the Hybrid Cloud

##### ISSUE TYPE

- New config Pull Request

##### COMPONENT NAME
config/base-aap2-infra

### CODE REVIEW

**Review by wilson-walrus — APPROVED** [review]
Looking good

**Review by newgoliath — CHANGES_REQUESTED** [review]
Requires enablement on this new style.  Completely opaque to ops.

**Comment by tonykay** [comment]
> Requires enablement on this new style. Completely opaque to ops.

Really not clear what this new style is. As I have tried to explain the Makefile is merely a form of documentation that allows self validation, it complements the README.adoc.

**Comment by tonykay** [comment]
> Requires enablement on this new style. Completely opaque to ops.

Same 5 playbooks as usual, same README, same requirements. invoked in the same way as usual? Only differences I see are 100% Fully Qualified Collection Names? What is _this new style_ It's just a simple config, almost identical but superseding ATE_BASE

**Pull request closed without merging**
