### PR TITLE
Add new feature in username distribution in JDG workshop

### PR DESCRIPTION
**Pull request by danieloh30**
##### SUMMARY

Add a new feature to enable individually block/unblock userids from admin GUI

##### ISSUE TYPE

- Feature Pull Request
- New config Pull Request

##### COMPONENT NAME

install-username-distribution.yaml

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by danieloh30** [comment]
@wkulhanek Any chance to have a look?

**Comment by danieloh30** [comment]
@stencell To try to understand your words clearly, how can we add someone to the role's owners? In the previous roles, only GPTE folks could review and merge PRs once someone created the PRs. Did you change the policy recently? If so, please add @sshaaf as the owner of this role b/c he created this role.

**Comment by wkulhanek** [comment]
@danieloh30 It's pretty simple. You can just add the file yourself in your PR. Example here: https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles_ocp_workloads/ocp4_workload_authentication/meta/main.yml

**Comment by danieloh30** [comment]
@wkulhanek Ok. so does that mean each workload has to add an owner as an author in main.yml? For example, ccnrd and quarkus workshop role don't have meta/main.yml so should I create the folder and file for this? can we add multiple authors? where can I find the guide(i.e license, min_ansible_version, galaxy_tags, dependencies, etc.) to create the meta/main.yaml?

**Comment by wkulhanek** [comment]
@danieloh30 Yes, please. We are writing a whole new contribution guide. Variable naming, authorship, support, etc. are all parts of making AgnosticD a more welcoming environment.

**Comment by danieloh30** [comment]
@stencell @wkulhanek Ok. I added metadata in main.yml. Can you approve and merge this to DEV CI?

**Comment by danieloh30** [comment]
@stencell thanks for the approval. Any chance to merge?

**Comment by danieloh30** [comment]
thanks @stencell

**Pull request merged**
