### PR TITLE
Updating Windows Containers Demo to use GA bits

### PR DESCRIPTION
**Pull request by christianh814**
##### SUMMARY

This updates this demo to use the Windows Containers GA bits.

##### ISSUE TYPE

- New config Pull Request

##### COMPONENT NAME

Windows Containers Operator

### CODE REVIEW

**Comment by christianh814** [comment]
cc: @wkulhanek

**Comment by stencell** [comment]
Can we take this opportunity since it is moving from community > production to set up a `CatalogSource` snapshot and not get bitten by updates to whatever the current CSV is that we are not expecting?

https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc

**Comment by christianh814** [comment]
@stencell Is there a central GPTE catolog snapshot that is used? Or do I have to 'host my own'?

**Comment by wkulhanek** [comment]
@christianh814 Technically you're supposed to use your own - so you have control over what's in it.
Having said that I just built updated ones today - you can use those if you want: 
Community: quay.io/gpte-devops-automation/olm_snapshot_community_catalog:v4.6_2021_01_05
Red Hat: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog:v4.6_2021_01_05

**Review by 9strands — APPROVED** [review]
Approving

**Pull request merged**
