### PR TITLE
Tl500 fix helm values

### PR DESCRIPTION
**Pull request by eformat**
##### SUMMARY

Update helm chart values files names (changed upstream)

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
TL500 Workshop

### CODE REVIEW

**Comment by eformat** [comment]
cc @d-jana

**Review by d-jana — APPROVED** [review]

**Comment by d-jana** [comment]
@eformat Please let me know if you want me to push it to production.

**Comment by eformat** [comment]
@d-jana ahh yes please push to prod !

**Comment by d-jana** [comment]
This is pushed to prod and tested successfully on production with GUID: `bdns7`.

**Pull request merged**
