### PR TITLE
Separate infra roles create new role dir 'roles-infra'

### PR DESCRIPTION
**Pull request by fridim**
##### SUMMARY

Prefer 'roles-infra' over the more natural 'infra-roles'  so it appears when
using tab completion when developing.

In the future, we can have other separations like for example:

- ocp workloads, 'roles-ocp-workloads'

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
all infra roles

### CODE REVIEW

**Comment by fridim** [comment]
I open this PR again now that i found where the issue was.

It was in the agnosticv script, see  https://github.com/redhat-gpe/OPEN_Admin/commit/a1ce89e453516537ae70319946bab7733c85d110

**Comment by fridim** [comment]
Tested in Babylon too: https://tower.dt-tower-dev.dev.open.redhat.com/#/jobs/playbook/2347?job_search=page_size:20;order_by:-finished;not__launch_type:sync

**Comment by ezr-ondrej** [comment]
Wouldn't be good to have: #1301?

**Comment by fridim** [comment]
> Wouldn't be good to have: #1301?

done

**Pull request merged**
