### PR TITLE
fixing image folder typo

### PR DESCRIPTION
**Pull request by amayagil**
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

03_Infrastructure/01_Foundational/04_Modify_a_base_config_Lab.adoc

### CODE REVIEW

**Comment by wkulhanek** [comment]
@amayagil Files are too large. Please resize.

**Comment by fridim** [comment]
You can also host it on AWS public GPTE S3 bucket  and have a link in your doc

**Comment by fridim** [comment]
@amayagil    please cleanup your PR by squashing your commits into one otherwise the LFS CHECK will not pass, since the big file is still part of the PR.

If you don't know how to, you can close and create a new PR without the commits introducing the big files

**Comment by amayagil** [comment]
will submit a clearer one

**Pull request closed without merging**
