### PR TITLE
Updated setup gitops file to add more edits to git repos

### PR DESCRIPTION
**Pull request by ritzshah**
##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by fridim — CHANGES_REQUESTED** [review]
using lineinfile to work with yaml files seems wrong to me.

Can't you use a template instead to generate the files?

**Comment by ritzshah** [comment]
The templates are already created but these are the ones I need to update the templates post cluster and gitea operator creation on the fly.

**Review by fridim — COMMENTED** [review]
delegating review to Wolfgang

**Comment by wkulhanek** [comment]
@fridim I'm afraid that's my pattern. :-( We have a Gitea repo with YAML Files that need to be updated for each individual user.

Maybe it _is_ time to look into Helm Charts instead...

**Review by wkulhanek — APPROVED** [review]

**Pull request merged**
