### PR TITLE
RH Summit 2024 Lab 1208 rosa workload deployment

### PR DESCRIPTION
**Pull request by augustrh**
##### SUMMARY

I've created a small role for the lab 1208 that deploys a kube manifest to create a Deployment on the ROSA clusters for the lab. The role is called ocp4_workload_managed_SMT2024_LB1208 and has been tested manually.

### CODE REVIEW

**Comment by augustrh** [comment]
I noticed it's failed a check on /home/runner/work/agnosticd/agnosticd/ansible/roles_ocp_workloads/ocp4_workload_managed_SMT2024_LB1208/files/application.yaml
but this is a custom file for our deployment and runs ok in testing.

**Comment by wkulhanek** [comment]
@augustrh You should just be able to use `>` to split the line to make it compliant.

As in
  annotations:
    ann1: >
      line1
      line1 continued
      line1 continued
You should be able to split it inside the var - like before a `}}`

**Comment by augustrh** [comment]
@wkulhanek but is that on application.yaml? that's just what i'm running against the cluster, not for deployment. (ie that's the code how I was given it)

**Comment by augustrh** [comment]
updated line lengths in application.yaml

**Comment by augustrh** [comment]
testing now with merged agv code.

**Comment by augustrh** [comment]
All tested and works.

**Pull request merged**
