### PR TITLE
Add RHEL lock version

### PR DESCRIPTION
**Pull request by marcosmamorim**
##### SUMMARY

Add task to lock RHEL in a specific version when using satellite

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
role/set-repositories

### CODE REVIEW

**Comment by stencell** [comment]
@marcosmamorim Can you give more information on what the problem is and why this is needed? This is a role used by many configs and needs extra care and understanding.

**Review by fridim — APPROVED** [review]

**Comment by fridim** [comment]
This is a common role, can you please explain why it is needed, what feature it gives, what usecase it serves, etc.
Can we have documentation along in the readme of the role ?
Thanks!

**Comment by wilson-walrus** [comment]
Hey guys, I think a cleaner solution to this will be the example below. This should not affect any current deployments and is just an additional option to lock a specific server to a release version within subscription-manager.

```
- name: Register with activation-key
  when: set_repositories_satellite_activationkey != ''
  redhat_subscription:
    state: present
    consumer_name: "{{ set_repositories_subscription_hostname }}"
    server_hostname: "{{ set_repositories_satellite_hostname }}"
    activationkey: "{{ set_repositories_satellite_activationkey }}"
    org_id: "{{ set_repositories_satellite_org | default(satellite_org) }}"
    release: "{{ set_repositories_release | default(omit) }}"
```

**Comment by 9strands** [comment]
Cleaning old PR entries at end of 2022

**Pull request closed without merging**
