### PR TITLE
OCP4 AIO Equinix - Setting version to main until we can get a new tag

### PR DESCRIPTION
**Pull request by bbethell-1**
Will need to change to a new tag one @agonzalezrh  is back tomorrow

### CODE REVIEW

**Review by d-jana — CHANGES_REQUESTED** [review]
can you create a tag and use that, rather than using a branch here to make PROD more stable

**Comment by bbethell-1** [comment]
> can you please create a tag and use that, rather than using a branch here to make PROD more stable?
> 

I don't have permission to create the branch as its on Albertos repo

**Comment by bbethell-1** [comment]
Aim to create one once Alberto returns tomorrow

**Comment by d-jana** [comment]
@agonzalezrh Can you please create tag on this repo so that we can use it in AgnosticD?

**Review by d-jana — APPROVED** [review]

**Pull request merged**
