### PR TITLE
tech-breakfix-shift-004 add binary grading script

### PR DESCRIPTION
**Pull request by ashish-k-s**
##### SUMMARY
Add binary version of grading script for the module

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by miteshget — COMMENTED** [review]
Binary file should be kept outside agnosticD as per guidelines.

**Comment by ashish-k-s** [comment]
> Binary file should be kept outside agnosticD as per guidelines.

Hi Mitesh,

This PR is based on our old catalog entries cee-cf-11[0,1,2] which were worked on long time back.
We had followed this practice in the above three catalogs 
I agree your suggestion and will keep that in mind for new catalog entries in the future.
But this request is not the new catalog creation from scratch but is based on existing catalog.
Let me know if this justification is enough for approval of this PR.
If not, I will have to re-work a big task.

**Comment by miteshget** [comment]
Hi @fridim, could you please review comment and PR?

**Comment by jkupferer** [comment]
@ashish-k-s Can you provide some background on what this binary is and where it is coming from? I see it appears to be a compiled executable?

**Comment by ashish-k-s** [comment]
> @ashish-k-s Can you provide some background on what this binary is and where it is coming from? I see it appears to be a compiled executable?

https://github.com/redhat-cop/agnosticd/blob/37d5956bd41ae4bbac0bdf4b7c513afb0b961c5a/ansible/roles_ocp_workloads/ocp4_workload_pntae/files/tech-breakfix-shift-004
Above is the text version of this script.
Associated training is a breakfix activity.
The script is converted to binary to hide the break and grading steps from learner.

**Review by jkupferer — APPROVED** [review]

**Comment by jkupferer** [comment]
@miteshget Approving. @ashish-k-s and I discussed. The break/fix script needs to be binary to avoid exposing the break code to lab users and so give away what needs fixed. Normally we would not allow binaries, but the binary is small and the rationale is clear. Making an exception for this case.

**Pull request merged**
