### PR TITLE
🐧 TL500 - 4.11 values file for base 🐧

### PR DESCRIPTION
**Pull request by eformat**
##### SUMMARY

Updates TL500 Workshop to 4.11

##### ISSUE TYPE
- New config Pull Request

### CODE REVIEW

**Review by wkulhanek — APPROVED** [review]

**Comment by eformat** [comment]
linked to

https://github.com/redhat-gpe/agnosticv/pull/7526

**Review by bbethell-1 — APPROVED** [review]

**Comment by eformat** [comment]
ping @9strands  .. can we do this one as well please 
linked to https://github.com/rhpds/agnosticv/pull/7526

**Comment by eformat** [comment]
@9strands  .. may as well merge this one as well please since https://github.com/rhpds/agnosticv/pull/7526 merged. Ta !

**Comment by 9strands** [comment]
@eformat - merged

**Pull request merged**
