### PR TITLE
Ensuring that insights nag doesn't exist

### PR DESCRIPTION
**Pull request by kincl**
##### SUMMARY

Minor fix to not nag about registering with Insights on the lab boxes

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

configs/rhel-container-security

### CODE REVIEW

**Comment by kincl** [comment]
@bbethell-1  fyi

**Comment by kincl** [comment]
@bbethell-1 can you review this one as well it came in about the same time as one of my other changes and probably got lost in the noise

**Review by bbethell-1 — APPROVED** [review]

**Comment by bbethell-1** [comment]
Hi @kincl  I have merged this now
Please can you let me know if you would like me to tag event with this added or if you have a Dev catalog item for this one to test it first? 
Many Thanks
Billy

**Comment by kincl** [comment]
Yes let's tag a new event item if it's not too much trouble

**Pull request merged**
