### PR TITLE
bugfix for sshpass

### PR DESCRIPTION
**Pull request by YogiSoni-lazy**
Bugfix Pull Request

##### COMPONENT NAME
osp17-director-deployment fixed the sshpass plaintext password in test.yaml

### CODE REVIEW

**Review by bbethell-1 — APPROVED** [review]

**Comment by bbethell-1** [comment]
@fridim  is this secure?

**Comment by fridim** [comment]
While it would be "secure", it would still be a static password, even if protected by gpg on this repo.

Best is to generate the password using ansible, when provisioning.

```yaml
-   set_fact:
        undercloud_ssh_password: "{{ lookup('password', '/dev/null length=18 chars=ascii_letters,digits') }}"
```

and return it to user if needed using `agnosticd_user_info`


```  agnosticd_user_info:
    data:
      undercloud_ssh_password: "{{ student_password }}"
```

Print it back to the user or not depends on the lab/demo.

**Comment by bbethell-1** [comment]
@YogiSoni-lazy  
Please can you adjust it to fit into Guillaume's suggestion
Thank you @fridim

**Comment by YogiSoni-lazy** [comment]
@fridim in this specific lab, there are total 6 vms provided with static passwords i.e r3dh4t1! for internal connectivity. I would like to highlight that learner is not going to take access of these vms and login using workstation vm that would be having password generated dynamically. 

So, do I need to generate all passwords dynamically? and if yes, then any reason why?

**Comment by fridim** [comment]
If the VMs are accessed internally, the usual pattern to provide access to them is to automate the creation of an SSH key on the workstation (or bastion) and to add it as authorized_key on the other instances.
That way, the student will not have to type passwords when SSH'ing from the workstation or bastion.

You can also re-use the provision SSH key for that purpose.

**Pull request closed without merging**
